### ISSUE TITLE
Feature Request: Micromanage packages for different functions?

### ISSUE THREAD

**Issue by pllim** [jbcurtin/bert-etl#6]
For example:

```python
@binding.follow('noop')
def func1():
    pass  # Only needs std lib

@binding.follow(func1, pipeline_type=constants.PipelineType.CONCURRENT)
def func2():
    pass  # Only needs numpy
```

It seems like currently, `bert-etl` puts all the packages in the environment in `func1.zip` and `func2.zip`, such that `func1.zip` would have `numpy` packaged even if it is not used there. Is it possible to micromanage which package goes into which ZIP?

Currently, it is not an issue for me, but if the ZIP files start to exceed 50 MB, this might become important.

No worries if this is too much work to be worthwhile. Feel free to close as "won't fix" if this is too complicated to implement.

**Comment by jbcurtin** [comment]
How about managing requirements from `bert-etl.yaml`? 
```
every_function:
  requirements: 
    - requests
    - boto3
    - std lib

func2:
  requirements:
    - numpy==1.17.1
    - sklearn
```

**Comment by pllim** [comment]
Yes, using the yaml would work. Though I am still thinking of a fool-proof way to do this, as a dependency can have dependencies that are unlisted. 🤔

**Comment by pllim** [comment]
Maybe it is easier to tell `bert-deploy.py` to stop after creating the lambda directories *before* zipping them up? Then I can go in and manually prune the directories... Or this is too much?

**Comment by jbcurtin** [comment]
I was thinking `requirements` would function similar `pip install -r requirements.txt`, if defined it'll install the requirements relative to each zip file. There is a syntax in `yaml` that'll allow you to copy properties from one definition to another. I'll have to play around with the syntax

what do you think?

```
every_function:
  requirements: 
    - requests
    - boto3
    - std lib

func2:
  requirements:
    <<: *every_function.requirements
    - numpy==1.17.1
    - sklearn
```

> lambda directories before zipping them up?

I'd like to offload as much of the manual intervention into `bert-etl.yam`l and API. Digging around in zip files, I feel would be asking to much of the engineer/scientist/developer.
